version: "3"
services:
  app:
    container_name: "fines_app"
    build: .
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL= jdbc:mysql://mysqldb:3306/prueba
      - DATABASE_USERNAME= root
      - DATABASE_PASSWORD= 123456
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "prueba"
      MYSQL_USER: "mvz"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"

volumes:
  mysql-data:
    external: false

